### ISSUE TITLE
Cookie based login will be deprecated soon. Does this library support OAuth?

### ISSUE THREAD

**Issue by clearitout** [sahilm/reddit.js#3]
https://www.reddit.com/r/redditdev/comments/2ujhkr/important_api_licensing_terms_clarified/

**Comment by sahilm** [comment]
From the readme:

> Reddit.js is a browser based wrapper on most of the read-only Reddit API. It makes CORS requests to    the Reddit API. Thus only unauthenicated (logged-out) requests are allowed.

**Comment by clearitout** [comment]
I saw that, but this library will not function after the new changes... I wasn't sure if you supported Implicit Based OAuth.
