### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by thany** [sahilm/reddit.js#8]
Trying to use this with Node 8.7.
The moment I try to anything with reddit.js, I get an error:
```
ReferenceError: window is not defined
```

My node script contains literally only this:
```javascript
const reddit = require("reddit.js");
```
And it crashes on that line, obviously.

**Comment by sahilm** [comment]
Thanks for trying out reddit.js. Unfortunately it cannot be used in node.js. It's only meant to be used inside a browser.
