### ISSUE TITLE
Add support for fetching multireddit data

### ISSUE THREAD

**Issue by PatMyron** [sahilm/reddit.js#9]
Reddit API Documentation:
https://www.reddit.com/dev/api/#GET_api_multi_{multipath}
"Fetch a multi's data and subreddit list by name."

Example endpoint:
https://www.reddit.com/api/multi/user/myroon5/m/nhl/

**Comment by sahilm** [comment]
Thanks for logging this. I think this project is past its prime. I'm archiving this project. Feel free to fork though :)
